### ISSUE TITLE
Cannot change port to different port than 8080

### ISSUE THREAD

**Issue by rclai** [kmagiera/babel-watch#48]
```
$ babel-watch ./src/index.js --port 8081
Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventEmitter.listen (/my-app/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/my-app/src/index.js:11:5)
    at Module._compile (module.js:570:32)
    at babelWatchLoader (/my-app/node_modules/babel-watch/runner.js:50:13)
    at Object.require.extensions.(anonymous function) [as .js] (/my-app/node_modules/babel-watch/runner.js:61:7)
```

**Comment by rclai** [comment]
Crap never mind.
