### ISSUE TITLE
babel-watch stuck on >>> RESTARTING <<<

### ISSUE THREAD

**Issue by fwielstra** [kmagiera/babel-watch#50]
I have a task in my package.json which does the following:

```
scripts: {
  "watch": "babel-watch tests/run-jasmine.js --presets es2015 --watch",
}
```

This used to work, but nowadays (in any 2.0.x version), the task stalls on `>>> RESTARTING <<<`. No significant cpu usage as far as I can tell. The only major change we did to our project recently was upgrade from Node 4.5 to Node 6.9/6.10, the latest LTS versions.

**Comment by levino** [comment]
I have the same here.

**Comment by zaaack** [comment]
Hit this problem, too. I'm using node v8.0.0 on macOS, seems child process doesn't trigger exit event after send kill signal.

Just add some workaround code in killAll function: 

```js

function killApp() {
  if (childApp) {
    const currentPipeFd = pipeFd;
    const currentPipeFilename = pipeFilename;
    let exitTriggered = false
    function handleExit() {
      if (currentPipeFd) {
        fs.close(currentPipeFd); // silently close pipe fd - ignore callback
      }
      if (currentPipeFilename) {
        fs.unlink(currentPipeFilename); // silently remove old pipe file - ignore callback
      }
      restartAppInternal();
    }
    childApp.on('exit', () => {
      exitTriggered = true
      handleExit()
    });
    try {
      childApp.kill('SIGHUP');
    } catch (error) {
      console.error(error)
      childApp.kill('SIGKILL');
    }
// restart anyway if childApp doesn't trigger exit event after 400ms
    setTimeout(() => {
      if (!exitTriggered) {
        // kill anyway
        childApp.kill('SIGKILL');
        handleExit()
      }
    }, 400)
    pipeFd = undefined;
    pipeFilename = undefined;
    childApp = undefined;
  }
}

```

**Comment by levino** [comment]
@zaaack Thanks for sharing. Not sure whether this does not lead to forgotten and still running processes. Also why do you not create a PR for this if it is a valuable solution?

**Comment by zaaack** [comment]
@Levino, it's just a temporary  workaround and could cause other issues, to really fix this issue we have more thing to do. I'm only using this in development environment, and if this workaround has other issues I'll find out.

**Comment by mjanssen** [comment]
@zaaack When will there be a fix pushed to the repo? The current version (2.0.7 on npmjs) still hangs on `>>> RESTARTING <<<` when an error occurs.

For now the fix above will help, but editing your modules feels kinda wrong.

**Comment by prasanna3000** [comment]
Tried the workaround but doesn't seem to work for me. Any other solution to fix this issue ?
This is what I see 
<pre>
>>> RESTARTING <<<
{ Error: kill ENOSYS
    at _errnoException (util.js:992:11)
    at ChildProcess.kill (internal/child_process.js:392:13)
    at killApp (path\node_modules\babel-watch\babel-watch.js:222:16)
    at prepareRestart (path\node_modules\babel-watch\babel-watch.js:246:5)
    at restartApp (path\node_modules\babel-watch\babel-watch.js:254:3)
    at FSWatcher.handleChange (path\node_modules\babel-watch\babel-watch.js:159:3)
    at invokeFunc (path\node_modules\lodash.debounce\index.js:160:19)
    at trailingEdge (path\node_modules\lodash.debounce\index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (path\node_modules\lodash.debounce\index.js:195:14)
    at ontimeout (timers.js:498:11) code: 'ENOSYS', errno: 'ENOSYS', syscall: 'kill' }
(node:9824) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>>> RESTARTING <<<
</pre>


Node Version: v8.11.4
OS: Windows

**Comment by STRML** [comment]
Could you try this with the latest version (`7.2.0`) @prasanna3000 ?

**Comment by prasanna3000** [comment]
> Could you try this with the latest version (`7.2.0`) @prasanna3000 ?

My babel-watch version is really old with 2.0.7 : )
I tried upgrading it to 7.2.0,  to get the following output


 throw new Error(`Plugin/Preset files are not allowed to export objects, only functions. In ${filepath}`);
    ^

Error: Plugin/Preset files are not allowed to export objects, only functions. In path\node_modules\babel-preset-es2015\lib\index.js
    at createDescriptor (path\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at items.map (path\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (path\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (path\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (path\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
    at mergeChainOpts (path\node_modules\@babel\core\lib\config\config-chain.js:416:26)
    at path\node_modules\@babel\core\lib\config\config-chain.js:374:7
    at Generator.next (<anonymous>)
    at loadFileChain (path\node_modules\@babel\core\lib\config\config-chain.js:228:24)
npm ERR! code ELIFECYCLE

I think it is because I changed only babel version....but not upgraded the code according to it. And to my surprise, the restart issue is encountered some times and at other times it is working as usual..
I do not have much experience in web development. Any solution to fix this or possible reasons behind facing it is very much appreciated

**Comment by STRML** [comment]
You need to upgrade your preset versions too.
