### ISSUE TITLE
"SyntaxError: Unexpected token import" when running babel-watch

### ISSUE THREAD

**Issue by stoikerty** [kmagiera/babel-watch#6]
Unfortunately, the issue I mentioned in the PR https://github.com/kmagiera/babel-watch/issues/2 is still present. The command I'm running is:

```
babel-watch --watch src --watch toolkit/webpack toolkit/webpack/development.js
```

This is the error I get is:

``` js
D:\_repos\universal-dev-toolkit\src\client\views\AppBody\Component.js:1
(function (exports, require, module, __filename, __dirname) { import React from 'react';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Module._extensions..js (module.js:432:10)
    at loader (D:\_repos\universal-dev-toolkit\node_modules\babel-watch\runner.js:14:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\_repos\universal-dev-toolkit\node_modules\babel-watch\runner.js:22:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (AppBody.js:5:1)
    at Module._compile (module.js:425:26)
    at loader (D:\_repos\universal-dev-toolkit\node_modules\babel-watch\runner.js:12:13)
    at Object.require.extensions.(anonymous function) [as .js] (D:\_repos\universal-dev-toolkit\node_modules\babel-watch\runner.js:22:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

See the [corresponding PR](https://github.com/stoikerty/universal-dev-toolkit/pull/3).

**Comment by kmagiera** [comment]
Hey @stoikerty  Sorry for keeping you waiting here for so long. I've just release version 2.0.0 that has "autowatch" functionality. This should allow you to no longer need to specify any `--watch` options as `babel-watch` will now detect which files are loaded by your program and start watching them automatically.

Please give it a shot when you have time and feel free to reopen this issue when it doesn't solve your problem.

**Comment by stoikerty** [comment]
You've basically excluded me with this update since you made it unix-only. I've tried it on a mac and although it seems to work at first glance, a lot of files don't get watched where-as other files seem to be compiled too often. I will hold off on integrating babel-watch into my toolkit for now since I'm looking for cross-compatible tools.

I also think that this issue should not be closed since it was never resolved (same with the one I had opened previously).

**Comment by nickhudkins** [comment]
@kmagiera fresh install of babel-watch, having the same issue where babelrc seems to be ignored. with or without --watch specified. OSX.

**Comment by nickhudkins** [comment]
Ah nevermind, I suspect this is an issue with running babel@6.18.2, I'll dig in some more

**Comment by jkk** [comment]
For the record, I'm on OSX and had the same issue. I tried upgrading all of my babel deps to the latest versions, reinstalled node_modules, still got "SyntaxError: Unexpected token import". I gave up and went back to nodemon. I don't have much time to troubleshoot, but willing to try any suggestions and report back.

**Comment by bunchjesse** [comment]
I'm seeing the same issue. 

I see no errors with this: `babel-node src/main.js`

I see `SyntaxError: Unexpected token import` errors with this: `babel-watch src/main.js`

**Comment by IAmJulianAcosta** [comment]
+1 on OSX

**Comment by markotom** [comment]
It doesn't work on OSX

**Comment by fatfatson** [comment]
+1  on Win10

**Comment by zenoven** [comment]
+1 on OSX

**Comment by zzswang** [comment]
+1 on OSX
