### ISSUE TITLE
Cannot read property 'list' of undefined when using with Babel 7

### ISSUE THREAD

**Issue by AfflatusX** [kmagiera/babel-watch#65]
Callstack: 
`TypeError: Cannot read property 'list' of undefined
    at Object.<anonymous> (/Users/txie/Reizo/editor/node_modules/babel-watch/babel-watch.js:30:56)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3`

Not sure if this is Babel 7 specific issue, has babel-watch been tested against babel-core 7 alpha?

**Comment by derrickbeining** [comment]
@kmagiera , any word on this? Anyone know a workaround?

**Comment by SterlingVix** [comment]
I'm also having this issue, as is the duplicate issue here: https://github.com/kmagiera/babel-watch/issues/89

My log:

```
/src/node_modules/babel-watch/babel-watch.js:30
program.option('-p, --plugins [string]', '', babel.util.list);
                                                        ^

TypeError: Cannot read property 'list' of undefined
    at Object.<anonymous> (/src/node_modules/babel-watch/babel-watch.js:30:57)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
```

I believe this is because `babel-watch` expects Babel v6.x, but Babel v7 breaks `babel.utils`:

https://github.com/kmagiera/babel-watch/blob/master/babel-watch.js

https://github.com/babel/babel/pull/5487 <-- removed in babel V7.

I think this is my issue, at least -- I am using Babel7.

**Comment by kaigouthro** [comment]
Same issue exact same error as above.

**Comment by stingrayfunk** [comment]
Any update on this?? Same is happening for me, preventing me from using babel-watch with the latest Babel 7.

My versions:

```
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.4",
    "@babel/node": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/plugin-proposal-do-expressions": "^7.0.0",
    "@babel/plugin-proposal-export-default-from": "^7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-proposal-function-bind": "^7.0.0",
    "@babel/plugin-proposal-function-sent": "^7.0.0",
    "@babel/plugin-proposal-json-strings": "^7.0.0",
    "@babel/plugin-proposal-logical-assignment-operators": "^7.0.0",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0",
    "@babel/plugin-proposal-numeric-separator": "^7.0.0",
    "@babel/plugin-proposal-optional-chaining": "^7.0.0",
    "@babel/plugin-proposal-pipeline-operator": "^7.0.0",
    "@babel/plugin-proposal-throw-expressions": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/polyfill": "^7.2.5",
    "@babel/preset-env": "^7.3.4",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.0.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^23.4.2",
    "babel-loader": "^8.0.5",
    "babel-watch": "^2.0.7",
```

**Comment by kmagiera** [comment]
cc @STRML

**Comment by STRML** [comment]
This should not be an issue in the latest version, have you tried it
@stingrayfunk?

**Comment by stingrayfunk** [comment]
Oops, silly me with the old version! Yes, upgrading fixes the issue. Thanks @STRML 👍

**Comment by STRML** [comment]
Great!
