### ISSUE TITLE
error babel-watch

### ISSUE THREAD

**Issue by sibelius** [kmagiera/babel-watch#7]
```
node_modules/babel-watch/runner.js:34
  if (filename.charAt(0) !== '/') {
              ^

TypeError: Cannot read property 'charAt' of undefined
    at process.<anonymous> (node_modules/babel-watch/runner.js:34:15)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
```

**Comment by sibelius** [comment]
this only happens when I pass one file to -w
